/* Generated by           cobc 4.0-early-dev.0 */
/* Generated from         TRANSF1A.cbl */
/* Generated at           ago 22 2025 22:24:07 */
/* GnuCOBOL build date    Sep 19 2022 04:28:17 */
/* GnuCOBOL package date  Jun 06 2020 20:56:36 UTC */
/* Compile command        cobc -x -g TRANSF1A.cbl */

/* Program local variables for 'TRANSF1A' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* File CONTA-ENT */
static cob_file		*h_CONTA_ENT = NULL;

/* File CONTA-SAI */
static cob_file		*h_CONTA_SAI = NULL;

/* File TXT-LOG */
static cob_file		*h_TXT_LOG = NULL;

/* Call pointers */
static cob_call_union	call_PROGDATA;
static cob_call_union	call_PROGTIME;

/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* WORKING-STORAGE Data */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_14[52] __attribute__((aligned));	/* CONTA-ENT Record */
static cob_u8_t	b_17[200] __attribute__((aligned));	/* CONTA-SAI Record */
static cob_u8_t	b_20[200] __attribute__((aligned));	/* TXT-LOG Record */
static cob_u8_t	b_21[10] __attribute__((aligned));	/* WS-CONTA-A */
static cob_u8_t	b_22[10] __attribute__((aligned));	/* WS-CONTA-B */
static cob_u8_t	b_23[20] __attribute__((aligned));	/* WS-VALOR-STR */
static cob_u8_t	b_24[11] __attribute__((aligned));	/* WS-VALOR */
static cob_u8_t	b_25[11] __attribute__((aligned));	/* F-SALDO */
static cob_u8_t	b_26[10] __attribute__((aligned));	/* A-NUM-CONTA */
static cob_u8_t	b_27[20] __attribute__((aligned));	/* A-NOME */
static cob_u8_t	b_28[11] __attribute__((aligned));	/* A-SALDO */
static cob_u8_t	b_29[10] __attribute__((aligned));	/* B-NUM-CONTA */
static cob_u8_t	b_30[20] __attribute__((aligned));	/* B-NOME */
static cob_u8_t	b_31[11] __attribute__((aligned));	/* B-SALDO */
static cob_u8_t	b_32[1] __attribute__((aligned));	/* WS-STATUS */
static cob_u8_t	b_35[1] __attribute__((aligned));	/* ENCONTROU-A */
static cob_u8_t	b_36[1] __attribute__((aligned));	/* ENCONTROU-B */
static cob_u8_t	b_37[8] __attribute__((aligned));	/* WS-DATE */
static cob_u8_t	b_38[6] __attribute__((aligned));	/* WS-TIME */
static cob_u8_t	b_39[12] __attribute__((aligned));	/* A-SALDO-EDIT */
static cob_u8_t	b_40[12] __attribute__((aligned));	/* B-SALDO-EDIT */
static cob_u8_t	b_41[12] __attribute__((aligned));	/* F-SALDO-EDIT */
static cob_u8_t	b_42[60] __attribute__((aligned));	/* WS-MOTIVO */
static cob_u8_t	b_43[2] __attribute__((aligned));	/* WRK-RETURN-CODE */
static cob_u8_t	b_44[1] __attribute__((aligned));	/* FIM-ARQUIVO */
static cob_u8_t	b_45[2] __attribute__((aligned));	/* WRK-IND1 */
static cob_u8_t	b_46[81] __attribute__((aligned));	/* COD001A-REGISTRO */

/* End of WORKING-STORAGE data */


/* Local Fields */
static cob_field f_2	= {4, (cob_u8_t *)&b_2, &a_8};	/* RETURN-CODE */
static cob_field f_8	= {52, b_14, &a_5};	/* FD-ENT-LINHA */
static cob_field f_9	= {10, b_14, &a_7};	/* F-NUM-CONTA */
static cob_field f_11	= {20, b_14 + 11, &a_2};	/* F-NOME */
static cob_field f_13	= {20, b_14 + 32, &a_2};	/* F-SALDO-STR */
static cob_field f_14	= {52, b_14, &a_2};	/* CONTA-ENT Record */
static cob_field f_15	= {200, b_17, &a_5};	/* WRK-SAI-REGISTRO */
static cob_field f_16	= {200, b_17, &a_2};	/* FD-SAI-LINHA */
static cob_field f_17	= {200, b_17, &a_2};	/* CONTA-SAI Record */
static cob_field f_18	= {200, b_20, &a_5};	/* WRK-LOG-REGISTRO */
static cob_field f_20	= {200, b_20, &a_2};	/* TXT-LOG Record */
static cob_field f_21	= {10, b_21, &a_7};	/* WS-CONTA-A */
static cob_field f_22	= {10, b_22, &a_7};	/* WS-CONTA-B */
static cob_field f_24	= {11, b_24, &a_3};	/* WS-VALOR */
static cob_field f_25	= {11, b_25, &a_3};	/* F-SALDO */
static cob_field f_26	= {10, b_26, &a_2};	/* A-NUM-CONTA */
static cob_field f_28	= {11, b_28, &a_3};	/* A-SALDO */
static cob_field f_29	= {10, b_29, &a_2};	/* B-NUM-CONTA */
static cob_field f_31	= {11, b_31, &a_3};	/* B-SALDO */
static cob_field f_35	= {1, b_35, &a_2};	/* ENCONTROU-A */
static cob_field f_36	= {1, b_36, &a_2};	/* ENCONTROU-B */
static cob_field f_39	= {12, b_39, &a_4};	/* A-SALDO-EDIT */
static cob_field f_40	= {12, b_40, &a_4};	/* B-SALDO-EDIT */
static cob_field f_41	= {12, b_41, &a_4};	/* F-SALDO-EDIT */
static cob_field f_42	= {60, b_42, &a_2};	/* WS-MOTIVO */
static cob_field f_43	= {2, b_43, &a_6};	/* WRK-RETURN-CODE */
static cob_field f_44	= {1, b_44, &a_2};	/* FIM-ARQUIVO */
static cob_field f_46	= {81, b_46, &a_5};	/* COD001A-REGISTRO */

/* End of fields */

