/* Generated by           cobc 4.0-early-dev.0 */
/* Generated from         TRANSF1A.cbl */
/* Generated at           ago 22 2025 22:24:07 */
/* GnuCOBOL build date    Sep 19 2022 04:28:17 */
/* GnuCOBOL package date  Jun 06 2020 20:56:36 UTC */
/* Compile command        cobc -x -g TRANSF1A.cbl */

#include <stdio.h>
#include <string.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"TRANSF1A.cbl"
#define  COB_PACKAGE_VERSION		"4.0-early-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"ago 22 2025 22:24:07"
#define  COB_MODULE_DATE		20250822
#define  COB_MODULE_TIME		222407

/* Global variables */
#include "TRANSF1A.c.h"

/* Function prototypes */

static int		TRANSF1A ();
static int		TRANSF1A_ (const int);
static void		TRANSF1A_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (TRANSF1A ());
}

/* Functions */

/* PROGRAM-ID 'TRANSF1A' */

/* ENTRY 'TRANSF1A' */

static int
TRANSF1A ()
{
  return TRANSF1A_ (0);
}

static int
TRANSF1A_ (const int entry)
{
  /* Program local variables */
  #include "TRANSF1A.c.l.h"

  /* Entry point name_hash values */
  static const unsigned int st_name_hash [] = {
  	0xF81962E5,	/* TRANSF1A */
  0};
  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, st_name_hash))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;
  if (frame_ptr == frame_overflow) {}

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Save number of call params */
  module->module_num_params = cob_glob_ptr->cob_call_params;

  goto l_2;
  cob_glob_ptr->cob_call_params = 0;

  /* PROCEDURE DIVISION */

  /* Line: 89        : Entry     TRANSF1A                : TRANSF1A.cbl */
  l_2:;

  /* Line: 96        : Section   0000-PROCESSAR          : TRANSF1A.cbl */
  /* Line: 99        : PERFORM            : TRANSF1A.cbl */
  module->module_stmt = 0x00100063;
  cob_trace_stmt (st_1);
  /* PERFORM 0001-OBTER-DATA */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 6;
  frame_ptr->return_address_ptr = &&l_39;
  goto l_6;
  l_39:
  frame_ptr--;
  /* Line: 100       : PERFORM            : TRANSF1A.cbl */
  module->module_stmt = 0x00100064;
  cob_trace_stmt (st_1);
  /* PERFORM 0002-OBTER-HORA */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 9;
  frame_ptr->return_address_ptr = &&l_40;
  goto l_9;
  l_40:
  frame_ptr--;
  /* Line: 101       : PERFORM            : TRANSF1A.cbl */
  module->module_stmt = 0x00100065;
  cob_trace_stmt (st_1);
  /* PERFORM 0003-INSERIR-TRANSF */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 12;
  frame_ptr->return_address_ptr = &&l_41;
  goto l_12;
  l_41:
  frame_ptr--;
  /* Line: 102       : IF                 : TRANSF1A.cbl */
  module->module_stmt = 0x00100066;
  cob_trace_stmt (st_2);
  if ( (cob_get_numdisp (b_32, 1) == 1) )
  {
    /* Line: 104       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x00100068;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 2, &c_1, &f_42);
    /* Line: 105       : PERFORM            : TRANSF1A.cbl */
    module->module_stmt = 0x00100069;
    cob_trace_stmt (st_1);
    /* PERFORM 9999-FINALIZAR */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 36;
    frame_ptr->return_address_ptr = &&l_42;
    goto l_36;
    l_42:
    frame_ptr--;
  }
  /* Line: 107       : PERFORM            : TRANSF1A.cbl */
  module->module_stmt = 0x0010006B;
  cob_trace_stmt (st_1);
  /* PERFORM 0005-CARREGAR-CONTAS */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 18;
  frame_ptr->return_address_ptr = &&l_43;
  goto l_18;
  l_43:
  frame_ptr--;
  /* Line: 108       : IF                 : TRANSF1A.cbl */
  module->module_stmt = 0x0010006C;
  cob_trace_stmt (st_2);
  if ( (cob_get_numdisp (b_32, 1) == 1) )
  {
    /* Line: 110       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x0010006E;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 2, &c_1, &f_42);
    /* Line: 111       : PERFORM            : TRANSF1A.cbl */
    module->module_stmt = 0x0010006F;
    cob_trace_stmt (st_1);
    /* PERFORM 9999-FINALIZAR */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 36;
    frame_ptr->return_address_ptr = &&l_44;
    goto l_36;
    l_44:
    frame_ptr--;
  }
  /* Line: 113       : MOVE               : TRANSF1A.cbl */
  module->module_stmt = 0x00100071;
  cob_trace_stmt (st_4);
  *(b_44) = 78;
  /* Line: 114       : PERFORM            : TRANSF1A.cbl */
  module->module_stmt = 0x00100072;
  cob_trace_stmt (st_1);
  /* PERFORM 0006-PROCESSAR-TRANSF */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 22;
  frame_ptr->return_address_ptr = &&l_45;
  goto l_22;
  l_45:
  frame_ptr--;
  /* Line: 115       : PERFORM            : TRANSF1A.cbl */
  module->module_stmt = 0x00100073;
  cob_trace_stmt (st_1);
  /* PERFORM 0007-ATUALIZAR-ARQUIVO */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 26;
  frame_ptr->return_address_ptr = &&l_46;
  goto l_26;
  l_46:
  frame_ptr--;
  /* Line: 117       : IF                 : TRANSF1A.cbl */
  module->module_stmt = 0x00100075;
  cob_trace_stmt (st_2);
  if ( (cob_get_numdisp (b_32, 1) == 0) )
  {
    /* Line: 118       : MOVE               : TRANSF1A.cbl */
    module->module_stmt = 0x00100076;
    cob_trace_stmt (st_4);
    cob_move (&f_28, &f_39);
    /* Line: 119       : MOVE               : TRANSF1A.cbl */
    module->module_stmt = 0x00100077;
    cob_trace_stmt (st_4);
    cob_move (&f_31, &f_40);
    /* Line: 120       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x00100078;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 1, &c_2);
    /* Line: 121       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x00100079;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 4, &c_3, &f_26, &c_4, &f_39);
    /* Line: 123       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x0010007B;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 4, &c_5, &f_29, &c_6, &f_40);
  }
  else
  {
    /* ELSE */
    /* Line: 126       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x0010007E;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 2, &c_7, &f_42);
  }
  /* Line: 129       : PERFORM            : TRANSF1A.cbl */
  module->module_stmt = 0x00100081;
  cob_trace_stmt (st_1);
  /* PERFORM 9999-FINALIZAR */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 36;
  frame_ptr->return_address_ptr = &&l_47;
  goto l_36;
  l_47:
  frame_ptr--;

  /* Line: 133       : Paragraph 0000-END                : TRANSF1A.cbl */
  /* Line: 133       : EXIT               : TRANSF1A.cbl */
  module->module_stmt = 0x00100085;
  cob_trace_stmt (st_5);

  /* Line: 140       : Section   0001-OBTER-DATA         : TRANSF1A.cbl */
  l_6:;
  /* Line: 143       : CALL               : TRANSF1A.cbl */
  module->module_stmt = 0x0010008F;
  cob_trace_stmt (st_6);
  cob_procedure_params[0] = &f_46;
  cob_glob_ptr->cob_call_params = 1;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_global_exception & 0x0b00) == 0x0b00)) cob_global_exception = 0;
    if (unlikely(call_PROGDATA.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
  {
    call_PROGDATA.funcvoid = cob_resolve_cobol ("PROGDATA", 0, 1);
  }
  cob_glob_ptr->cob_call_name_hash = 0x814469E6;
  COB_RESET_EXCEPTION (0);
  b_2 = ((int (*)(void *))call_PROGDATA.funcint) (b_46);
  /* Line: 145       : MOVE               : TRANSF1A.cbl */
  module->module_stmt = 0x00100091;
  cob_trace_stmt (st_4);
  cob_set_int (&f_43, b_2);
  /* Line: 147       : IF                 : TRANSF1A.cbl */
  module->module_stmt = 0x00100093;
  cob_trace_stmt (st_2);
  if (((int)cob_cmpswp_s16 (b_43, 0LL) != 0))
  {
    /* Line: 148       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x00100094;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 2, &c_8, &f_43);
    /* Line: 150       : STOP RUN           : TRANSF1A.cbl */
    module->module_stmt = 0x00100096;
    cob_trace_stmt (st_7);
    cob_stop_run (b_2);
  }
  /* Line: 153       : MOVE               : TRANSF1A.cbl */
  module->module_stmt = 0x00100099;
  cob_trace_stmt (st_4);
  memcpy (b_37 + 0, b_46, 4);
  /* Line: 154       : MOVE               : TRANSF1A.cbl */
  module->module_stmt = 0x0010009A;
  cob_trace_stmt (st_4);
  memcpy (b_37 + 4, b_46 + 4, 2);
  /* Line: 155       : MOVE               : TRANSF1A.cbl */
  module->module_stmt = 0x0010009B;
  cob_trace_stmt (st_4);
  memcpy (b_37 + 6, b_46 + 6, 2);

  /* Line: 159       : Paragraph 0001-END                : TRANSF1A.cbl */
  /* Line: 159       : EXIT               : TRANSF1A.cbl */
  module->module_stmt = 0x0010009F;
  cob_trace_stmt (st_5);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 166       : Section   0002-OBTER-HORA         : TRANSF1A.cbl */
  l_9:;
  /* Line: 169       : CALL               : TRANSF1A.cbl */
  module->module_stmt = 0x001000A9;
  cob_trace_stmt (st_6);
  cob_procedure_params[0] = &f_46;
  cob_glob_ptr->cob_call_params = 1;
  cob_glob_ptr->cob_stmt_exception = 0;
  if (unlikely((cob_global_exception & 0x0b00) == 0x0b00)) cob_global_exception = 0;
    if (unlikely(call_PROGTIME.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
  {
    call_PROGTIME.funcvoid = cob_resolve_cobol ("PROGTIME", 0, 1);
  }
  cob_glob_ptr->cob_call_name_hash = 0x817D622E;
  COB_RESET_EXCEPTION (0);
  b_2 = ((int (*)(void *))call_PROGTIME.funcint) (b_46);
  /* Line: 171       : MOVE               : TRANSF1A.cbl */
  module->module_stmt = 0x001000AB;
  cob_trace_stmt (st_4);
  cob_set_int (&f_43, b_2);
  /* Line: 173       : IF                 : TRANSF1A.cbl */
  module->module_stmt = 0x001000AD;
  cob_trace_stmt (st_2);
  if (((int)cob_cmpswp_s16 (b_43, 0LL) != 0))
  {
    /* Line: 174       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x001000AE;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 2, &c_8, &f_43);
    /* Line: 176       : STOP RUN           : TRANSF1A.cbl */
    module->module_stmt = 0x001000B0;
    cob_trace_stmt (st_7);
    cob_stop_run (b_2);
  }
  /* Line: 179       : MOVE               : TRANSF1A.cbl */
  module->module_stmt = 0x001000B3;
  cob_trace_stmt (st_4);
  memcpy (b_38 + 0, b_46 + 53, 2);
  /* Line: 180       : MOVE               : TRANSF1A.cbl */
  module->module_stmt = 0x001000B4;
  cob_trace_stmt (st_4);
  memcpy (b_38 + 2, b_46 + 55, 2);
  /* Line: 181       : MOVE               : TRANSF1A.cbl */
  module->module_stmt = 0x001000B5;
  cob_trace_stmt (st_4);
  memcpy (b_38 + 4, b_46 + 57, 2);

  /* Line: 185       : Paragraph 0002-END                : TRANSF1A.cbl */
  /* Line: 185       : EXIT               : TRANSF1A.cbl */
  module->module_stmt = 0x001000B9;
  cob_trace_stmt (st_5);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Line: 192       : Section   0003-INSERIR-TRANSF     : TRANSF1A.cbl */
  l_12:;
  /* Line: 195       : DISPLAY            : TRANSF1A.cbl */
  module->module_stmt = 0x001000C3;
  cob_trace_stmt (st_3);
  cob_display (0, 0, 1, &c_9);
  /* Line: 197       : ACCEPT             : TRANSF1A.cbl */
  module->module_stmt = 0x001000C5;
  cob_trace_stmt (st_8);
  cob_accept (&f_21);
  /* Line: 199       : DISPLAY            : TRANSF1A.cbl */
  module->module_stmt = 0x001000C7;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &c_10);
  /* Line: 200       : ACCEPT             : TRANSF1A.cbl */
  module->module_stmt = 0x001000C8;
  cob_trace_stmt (st_8);
  cob_accept (&f_22);
  /* Line: 202       : DISPLAY            : TRANSF1A.cbl */
  module->module_stmt = 0x001000CA;
  cob_trace_stmt (st_3);
  cob_display (0, 0, 1, &c_11);
  /* Line: 205       : ACCEPT             : TRANSF1A.cbl */
  module->module_stmt = 0x001000CD;
  cob_trace_stmt (st_8);
  cob_accept (&f_24);
  /* Line: 207       : PERFORM            : TRANSF1A.cbl */
  module->module_stmt = 0x001000CF;
  cob_trace_stmt (st_1);
  /* PERFORM 0004-VALIDAR-ENTRADA */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 15;
  frame_ptr->return_address_ptr = &&l_48;
  goto l_15;
  l_48:
  frame_ptr--;

  /* Line: 211       : Paragraph 0003-END                : TRANSF1A.cbl */
  /* Line: 211       : EXIT               : TRANSF1A.cbl */
  module->module_stmt = 0x001000D3;
  cob_trace_stmt (st_5);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 12)
    goto *frame_ptr->return_address_ptr;

  /* Line: 220       : Section   0004-VALIDAR-ENTRADA    : TRANSF1A.cbl */
  l_15:;
  /* Line: 223       : IF                 : TRANSF1A.cbl */
  module->module_stmt = 0x001000DF;
  cob_trace_stmt (st_2);
  if (((int)memcmp (b_21, b_22, 10) == 0))
  {
    /* Line: 224       : SET                : TRANSF1A.cbl */
    module->module_stmt = 0x001000E0;
    cob_trace_stmt (st_9);
    *(b_32) = 49;
    /* Line: 225       : MOVE               : TRANSF1A.cbl */
    module->module_stmt = 0x001000E1;
    cob_trace_stmt (st_4);
    cob_move ((cob_field *)&c_12, &f_42);
  }
  /* Line: 232       : IF                 : TRANSF1A.cbl */
  module->module_stmt = 0x001000E8;
  cob_trace_stmt (st_2);
  if (((int)cob_cmp_llint (&f_24, 0LL) == 0))
  {
    /* Line: 233       : SET                : TRANSF1A.cbl */
    module->module_stmt = 0x001000E9;
    cob_trace_stmt (st_9);
    *(b_32) = 49;
    /* Line: 234       : MOVE               : TRANSF1A.cbl */
    module->module_stmt = 0x001000EA;
    cob_trace_stmt (st_4);
    cob_move ((cob_field *)&c_13, &f_42);
  }
  /* Line: 238       : SET                : TRANSF1A.cbl */
  module->module_stmt = 0x001000EE;
  cob_trace_stmt (st_9);
  *(b_32) = 48;

  /* Line: 242       : Paragraph 0004-END                : TRANSF1A.cbl */
  /* Line: 242       : EXIT               : TRANSF1A.cbl */
  module->module_stmt = 0x001000F2;
  cob_trace_stmt (st_5);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 15)
    goto *frame_ptr->return_address_ptr;

  /* Line: 249       : Section   0005-CARREGAR-CONTAS    : TRANSF1A.cbl */
  l_18:;
  /* Line: 252       : DISPLAY            : TRANSF1A.cbl */
  module->module_stmt = 0x001000FC;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &c_14);
  /* Line: 254       : OPEN               : TRANSF1A.cbl */
  module->module_stmt = 0x001000FE;
  cob_trace_stmt (st_10);
  cob_open (h_CONTA_ENT, 1, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_49;
    goto l_1;
    l_49:
    frame_ptr--;
  }
  /* Line: 256       : PERFORM            : TRANSF1A.cbl */
  module->module_stmt = 0x00100100;
  cob_trace_stmt (st_1);
  for (;;)
  {
    if ((((int)(int)(*(b_44) - 83) == 0) || 
        (((int)(int)(*(b_35) - 83) == 0) && 
        ((int)(int)(*(b_36) - 83) == 0))))
      break;
    /* Line: 259       : READ               : TRANSF1A.cbl */
    module->module_stmt = 0x00100103;
    cob_trace_stmt (st_11);
    cob_read_next (h_CONTA_ENT, NULL, 1);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0501)
      {
        /* Line: 260       : MOVE               : TRANSF1A.cbl */
        module->module_stmt = 0x00100104;
        cob_trace_stmt (st_4);
        *(b_44) = 83;
      }
      else
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_50;
        goto l_1;
        l_50:
        frame_ptr--;
      }
    }
    /* Line: 263       : MOVE               : TRANSF1A.cbl */
    module->module_stmt = 0x00100107;
    cob_trace_stmt (st_4);
    *(b_35) = 78;
    *(b_36) = 78;
    /* Line: 274       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x00100112;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 2, &c_15, &f_9);
    /* Line: 275       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x00100113;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 2, &c_16, &f_21);
    /* Line: 276       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x00100114;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 2, &c_17, &f_22);
    /* Line: 278       : IF                 : TRANSF1A.cbl */
    module->module_stmt = 0x00100116;
    cob_trace_stmt (st_2);
    if (((int)memcmp (b_14, b_21, 10) == 0))
    {
      /* Line: 279       : MOVE               : TRANSF1A.cbl */
      module->module_stmt = 0x00100117;
      cob_trace_stmt (st_4);
      memcpy (b_26, b_14, 10);
      /* Line: 280       : MOVE               : TRANSF1A.cbl */
      module->module_stmt = 0x00100118;
      cob_trace_stmt (st_4);
      memcpy (b_27, b_14 + 11, 20);
      /* Line: 281       : MOVE               : TRANSF1A.cbl */
      module->module_stmt = 0x00100119;
      cob_trace_stmt (st_4);
      memcpy (b_28, b_25, 11);
      /* Line: 282       : MOVE               : TRANSF1A.cbl */
      module->module_stmt = 0x0010011A;
      cob_trace_stmt (st_4);
      *(b_35) = 83;
    }
    /* Line: 285       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x0010011D;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 2, &c_18, &f_35);
    /* Line: 286       : IF                 : TRANSF1A.cbl */
    module->module_stmt = 0x0010011E;
    cob_trace_stmt (st_2);
    if (((int)memcmp (b_14, b_22, 10) == 0))
    {
      /* Line: 287       : MOVE               : TRANSF1A.cbl */
      module->module_stmt = 0x0010011F;
      cob_trace_stmt (st_4);
      memcpy (b_29, b_14, 10);
      /* Line: 288       : MOVE               : TRANSF1A.cbl */
      module->module_stmt = 0x00100120;
      cob_trace_stmt (st_4);
      memcpy (b_30, b_14 + 11, 20);
      /* Line: 289       : MOVE               : TRANSF1A.cbl */
      module->module_stmt = 0x00100121;
      cob_trace_stmt (st_4);
      memcpy (b_31, b_25, 11);
      /* Line: 290       : MOVE               : TRANSF1A.cbl */
      module->module_stmt = 0x00100122;
      cob_trace_stmt (st_4);
      *(b_36) = 83;
    }
    /* Line: 292       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x00100124;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 2, &c_19, &f_36);
  }
  /* Line: 295       : CLOSE              : TRANSF1A.cbl */
  module->module_stmt = 0x00100127;
  cob_trace_stmt (st_12);
  cob_close (h_CONTA_ENT, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_51;
    goto l_1;
    l_51:
    frame_ptr--;
  }
  /* Line: 297       : IF                 : TRANSF1A.cbl */
  module->module_stmt = 0x00100129;
  cob_trace_stmt (st_2);
  if (((int)(int)(*(b_35) - 83) != 0))
  {
    /* Line: 298       : SET                : TRANSF1A.cbl */
    module->module_stmt = 0x0010012A;
    cob_trace_stmt (st_9);
    *(b_32) = 49;
    /* Line: 299       : MOVE               : TRANSF1A.cbl */
    module->module_stmt = 0x0010012B;
    cob_trace_stmt (st_4);
    cob_move ((cob_field *)&c_20, &f_42);
    /* Line: 300       : EXIT PARAGRAPH     : TRANSF1A.cbl */
    module->module_stmt = 0x0010012C;
    cob_trace_stmt (st_13);
    goto l_20;
  }
  /* Line: 302       : IF                 : TRANSF1A.cbl */
  module->module_stmt = 0x0010012E;
  cob_trace_stmt (st_2);
  if (((int)(int)(*(b_36) - 83) != 0))
  {
    /* Line: 303       : SET                : TRANSF1A.cbl */
    module->module_stmt = 0x0010012F;
    cob_trace_stmt (st_9);
    *(b_32) = 49;
    /* Line: 304       : MOVE               : TRANSF1A.cbl */
    module->module_stmt = 0x00100130;
    cob_trace_stmt (st_4);
    cob_move ((cob_field *)&c_21, &f_42);
    /* Line: 305       : EXIT PARAGRAPH     : TRANSF1A.cbl */
    module->module_stmt = 0x00100131;
    cob_trace_stmt (st_13);
    goto l_20;
  }
  /* Line: 308       : SET                : TRANSF1A.cbl */
  module->module_stmt = 0x00100134;
  cob_trace_stmt (st_9);
  *(b_32) = 48;

  /* Implicit EXIT label */
  l_20:;

  /* Line: 312       : Paragraph 0005-END                : TRANSF1A.cbl */
  /* Line: 312       : EXIT               : TRANSF1A.cbl */
  module->module_stmt = 0x00100138;
  cob_trace_stmt (st_5);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 18)
    goto *frame_ptr->return_address_ptr;

  /* Line: 319       : Section   0006-PROCESSAR-TRANSF   : TRANSF1A.cbl */
  l_22:;
  /* Line: 322       : DISPLAY            : TRANSF1A.cbl */
  module->module_stmt = 0x00100142;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &c_22);
  /* Line: 324       : IF                 : TRANSF1A.cbl */
  module->module_stmt = 0x00100144;
  cob_trace_stmt (st_2);
  if (((int)memcmp (b_28, b_24, 11) < 0))
  {
    /* Line: 325       : SET                : TRANSF1A.cbl */
    module->module_stmt = 0x00100145;
    cob_trace_stmt (st_9);
    *(b_32) = 49;
    /* Line: 326       : MOVE               : TRANSF1A.cbl */
    module->module_stmt = 0x00100146;
    cob_trace_stmt (st_4);
    cob_move ((cob_field *)&c_23, &f_42);
  }
  /* Line: 330       : DISPLAY            : TRANSF1A.cbl */
  module->module_stmt = 0x0010014A;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 2, &c_24, &f_24);
  /* Line: 331       : SUBTRACT           : TRANSF1A.cbl */
  module->module_stmt = 0x0010014B;
  cob_trace_stmt (st_14);
  COB_RESET_EXCEPTION (0);
  cob_sub (&f_28, &f_24, 2);
  if (unlikely ((cob_glob_ptr->cob_exception_code & 0xff00) == 0x1000))
  {
    /* Line: 333       : SET                : TRANSF1A.cbl */
    module->module_stmt = 0x0010014D;
    cob_trace_stmt (st_9);
    *(b_32) = 49;
    /* Line: 334       : MOVE               : TRANSF1A.cbl */
    module->module_stmt = 0x0010014E;
    cob_trace_stmt (st_4);
    cob_move ((cob_field *)&c_25, &f_42);
    /* Line: 335       : EXIT PARAGRAPH     : TRANSF1A.cbl */
    module->module_stmt = 0x0010014F;
    cob_trace_stmt (st_13);
    goto l_24;
  }
  /* Line: 338       : DISPLAY            : TRANSF1A.cbl */
  module->module_stmt = 0x00100152;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 2, &c_26, &f_24);
  /* Line: 340       : ADD                : TRANSF1A.cbl */
  module->module_stmt = 0x00100154;
  cob_trace_stmt (st_15);
  COB_RESET_EXCEPTION (0);
  cob_add (&f_31, &f_24, 2);
  if (unlikely ((cob_glob_ptr->cob_exception_code & 0xff00) == 0x1000))
  {
    /* Line: 343       : ADD                : TRANSF1A.cbl */
    module->module_stmt = 0x00100157;
    cob_trace_stmt (st_15);
    cob_add (&f_28, &f_24, 0);
    /* Line: 344       : SET                : TRANSF1A.cbl */
    module->module_stmt = 0x00100158;
    cob_trace_stmt (st_9);
    *(b_32) = 49;
    /* Line: 345       : MOVE               : TRANSF1A.cbl */
    module->module_stmt = 0x00100159;
    cob_trace_stmt (st_4);
    cob_move ((cob_field *)&c_27, &f_42);
    /* Line: 346       : EXIT PARAGRAPH     : TRANSF1A.cbl */
    module->module_stmt = 0x0010015A;
    cob_trace_stmt (st_13);
    goto l_24;
  }
  /* Line: 350       : PERFORM            : TRANSF1A.cbl */
  module->module_stmt = 0x0010015E;
  cob_trace_stmt (st_1);
  /* PERFORM 0007-ATUALIZAR-ARQUIVO */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
  	cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 26;
  frame_ptr->return_address_ptr = &&l_52;
  goto l_26;
  l_52:
  frame_ptr--;

  /* Implicit EXIT label */
  l_24:;

  /* Line: 354       : Paragraph 0006-END                : TRANSF1A.cbl */
  /* Line: 354       : EXIT               : TRANSF1A.cbl */
  module->module_stmt = 0x00100162;
  cob_trace_stmt (st_5);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 22)
    goto *frame_ptr->return_address_ptr;

  /* Line: 361       : Section   0007-ATUALIZAR-ARQUIVO  : TRANSF1A.cbl */
  l_26:;
  /* Line: 364       : DISPLAY            : TRANSF1A.cbl */
  module->module_stmt = 0x0010016C;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &c_28);
  /* Line: 365       : OPEN               : TRANSF1A.cbl */
  module->module_stmt = 0x0010016D;
  cob_trace_stmt (st_10);
  cob_open (h_CONTA_ENT, 1, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_53;
    goto l_1;
    l_53:
    frame_ptr--;
  }
  /* Line: 366       : OPEN               : TRANSF1A.cbl */
  module->module_stmt = 0x0010016E;
  cob_trace_stmt (st_10);
  cob_open (h_CONTA_SAI, 2, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_54;
    goto l_1;
    l_54:
    frame_ptr--;
  }
  /* Line: 368       : PERFORM            : TRANSF1A.cbl */
  module->module_stmt = 0x00100170;
  cob_trace_stmt (st_1);
  for (;;)
  {
    if (((int)(int)(*(b_44) - 83) == 0))
      break;
    /* Line: 369       : READ               : TRANSF1A.cbl */
    module->module_stmt = 0x00100171;
    cob_trace_stmt (st_11);
    cob_read_next (h_CONTA_ENT, NULL, 1);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      if (cob_glob_ptr->cob_exception_code == 0x0501)
      {
        /* Line: 370       : MOVE               : TRANSF1A.cbl */
        module->module_stmt = 0x00100172;
        cob_trace_stmt (st_4);
        *(b_44) = 83;
      }
      else
      {
        /* PERFORM Default Error Handler */
        frame_ptr++;
        if (unlikely(frame_ptr == frame_overflow))
        	cob_fatal_error (COB_FERROR_STACK);
        frame_ptr->perform_through = 1;
        frame_ptr->return_address_ptr = &&l_55;
        goto l_1;
        l_55:
        frame_ptr--;
      }
    }
    /* Line: 373       : MOVE               : TRANSF1A.cbl */
    module->module_stmt = 0x00100175;
    cob_trace_stmt (st_4);
    memset (b_14, 48, 10);
    /* Line: 374       : MOVE               : TRANSF1A.cbl */
    module->module_stmt = 0x00100176;
    cob_trace_stmt (st_4);
    memset (b_14 + 11, 32, 20);
    memset (b_14 + 32, 32, 20);
    /* Line: 375       : UNSTRING           : TRANSF1A.cbl */
    module->module_stmt = 0x00100177;
    cob_trace_stmt (st_16);
    cob_unstring_init (&f_8, NULL, 1);
    cob_unstring_delimited ((cob_field *)&c_29, 0);
    cob_unstring_into (&f_9, 0, 0);
    cob_unstring_into (&f_11, 0, 0);
    cob_unstring_into (&f_13, 0, 0);
    cob_unstring_finish ();
    /* Line: 382       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x0010017E;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 2, &c_30, &f_9);
    /* Line: 383       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x0010017F;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 2, &c_31, &f_11);
    /* Line: 384       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x00100180;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 2, &c_32, &f_13);
    /* Line: 386       : EVALUATE           : TRANSF1A.cbl */
    module->module_stmt = 0x00100182;
    cob_trace_stmt (st_17);

    /* Line: 387       : WHEN               : TRANSF1A.cbl */
    module->module_stmt = 0x00100183;
    cob_trace_stmt (st_18);

    if (((int)cob_cmp (&f_9, &f_26) == 0))
    {
      /* Line: 388       : MOVE               : TRANSF1A.cbl */
      module->module_stmt = 0x00100184;
      cob_trace_stmt (st_4);
      memcpy (b_25, b_28, 11);
      goto l_28;
    }

    /* Line: 389       : WHEN               : TRANSF1A.cbl */
    module->module_stmt = 0x00100185;
    cob_trace_stmt (st_18);

    if (((int)cob_cmp (&f_9, &f_29) == 0))
    {
      /* Line: 390       : MOVE               : TRANSF1A.cbl */
      module->module_stmt = 0x00100186;
      cob_trace_stmt (st_4);
      memcpy (b_25, b_31, 11);
      goto l_28;
    }

    /* WHEN OTHER */
    /* Line: 392       : CONTINUE           : TRANSF1A.cbl */
    module->module_stmt = 0x00100188;
    cob_trace_stmt (st_19);
    ;

    /* End EVALUATE */
    l_28:;
    /* Line: 395       : MOVE               : TRANSF1A.cbl */
    module->module_stmt = 0x0010018B;
    cob_trace_stmt (st_4);
    cob_move (&f_25, &f_41);
    /* Line: 397       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x0010018D;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 2, &c_33, &f_41);
    /* Line: 399       : STRING             : TRANSF1A.cbl */
    module->module_stmt = 0x0010018F;
    cob_trace_stmt (st_20);
    cob_string_init (&f_16, NULL);
    cob_string_delimited (NULL);
    cob_string_append (&f_9);
    cob_string_delimited (NULL);
    cob_string_append ((cob_field *)&c_29);
    cob_string_delimited (NULL);
    cob_string_append (&f_11);
    cob_string_delimited (NULL);
    cob_string_append ((cob_field *)&c_29);
    cob_string_delimited (NULL);
    cob_string_append (&f_41);
    cob_string_finish ();
    /* Line: 408       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x00100198;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 1, &c_34);
    /* Line: 410       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x0010019A;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 2, &c_35, &f_16);
    /* Line: 411       : WRITE              : TRANSF1A.cbl */
    module->module_stmt = 0x0010019B;
    cob_trace_stmt (st_21);
    cob_move (&f_8, &f_15);
    cob_write (h_CONTA_SAI, &f_15, 2162689, NULL, 0);
    if (unlikely(cob_glob_ptr->cob_exception_code != 0))
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_56;
      goto l_1;
      l_56:
      frame_ptr--;
    }
    /* Line: 412       : DISPLAY            : TRANSF1A.cbl */
    module->module_stmt = 0x0010019C;
    cob_trace_stmt (st_3);
    cob_display (0, 1, 1, &c_36);
  }
  /* Line: 415       : CLOSE              : TRANSF1A.cbl */
  module->module_stmt = 0x0010019F;
  cob_trace_stmt (st_12);
  cob_close (h_CONTA_ENT, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_57;
    goto l_1;
    l_57:
    frame_ptr--;
  }
  /* Line: 416       : CLOSE              : TRANSF1A.cbl */
  module->module_stmt = 0x001001A0;
  cob_trace_stmt (st_12);
  cob_close (h_CONTA_SAI, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_58;
    goto l_1;
    l_58:
    frame_ptr--;
  }
  /* Line: 418       : SET                : TRANSF1A.cbl */
  module->module_stmt = 0x001001A2;
  cob_trace_stmt (st_9);
  *(b_32) = 48;
  /* Line: 419       : MOVE               : TRANSF1A.cbl */
  module->module_stmt = 0x001001A3;
  cob_trace_stmt (st_4);
  cob_move ((cob_field *)&c_37, &f_42);

  /* Line: 425       : Paragraph 0007-END                : TRANSF1A.cbl */
  /* Line: 425       : EXIT               : TRANSF1A.cbl */
  module->module_stmt = 0x001001A9;
  cob_trace_stmt (st_5);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 26)
    goto *frame_ptr->return_address_ptr;

  /* Line: 432       : Section   0008-GRAVAR-LOG         : TRANSF1A.cbl */
  /* Line: 435       : DISPLAY            : TRANSF1A.cbl */
  module->module_stmt = 0x001001B3;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &c_38);
  /* Line: 437       : MOVE               : TRANSF1A.cbl */
  module->module_stmt = 0x001001B5;
  cob_trace_stmt (st_4);
  cob_move (&f_28, &f_39);
  /* Line: 438       : MOVE               : TRANSF1A.cbl */
  module->module_stmt = 0x001001B6;
  cob_trace_stmt (st_4);
  cob_move (&f_31, &f_40);
  /* Line: 441       : MOVE               : TRANSF1A.cbl */
  module->module_stmt = 0x001001B9;
  cob_trace_stmt (st_4);
  cob_move ((cob_field *)&c_39, &f_18);
  /* Line: 453       : DISPLAY            : TRANSF1A.cbl */
  module->module_stmt = 0x001001C5;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &c_40);
  /* Line: 455       : OPEN               : TRANSF1A.cbl */
  module->module_stmt = 0x001001C7;
  cob_trace_stmt (st_10);
  cob_open (h_TXT_LOG, 1, 0, NULL);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_59;
    goto l_1;
    l_59:
    frame_ptr--;
  }
  /* Line: 456       : WRITE              : TRANSF1A.cbl */
  module->module_stmt = 0x001001C8;
  cob_trace_stmt (st_21);
  cob_write (h_TXT_LOG, &f_18, 2162689, NULL, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_60;
    goto l_1;
    l_60:
    frame_ptr--;
  }
  /* Line: 457       : DISPLAY            : TRANSF1A.cbl */
  module->module_stmt = 0x001001C9;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &c_41);
  /* Line: 458       : CLOSE              : TRANSF1A.cbl */
  module->module_stmt = 0x001001CA;
  cob_trace_stmt (st_12);
  cob_close (h_TXT_LOG, NULL, 0, 0);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    /* PERFORM Default Error Handler */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
    	cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 1;
    frame_ptr->return_address_ptr = &&l_61;
    goto l_1;
    l_61:
    frame_ptr--;
  }

  /* Line: 462       : Paragraph 0008-END                : TRANSF1A.cbl */
  /* Line: 462       : EXIT               : TRANSF1A.cbl */
  module->module_stmt = 0x001001CE;
  cob_trace_stmt (st_5);

  /* Line: 469       : Section   0009-LER-CONTA-ENT      : TRANSF1A.cbl */
  /* Line: 472       : DISPLAY            : TRANSF1A.cbl */
  module->module_stmt = 0x001001D8;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &c_42);
  /* Line: 474       : READ               : TRANSF1A.cbl */
  module->module_stmt = 0x001001DA;
  cob_trace_stmt (st_11);
  cob_read_next (h_CONTA_ENT, NULL, 1);
  if (unlikely(cob_glob_ptr->cob_exception_code != 0))
  {
    if (cob_glob_ptr->cob_exception_code == 0x0501)
    {
      /* Line: 475       : MOVE               : TRANSF1A.cbl */
      module->module_stmt = 0x001001DB;
      cob_trace_stmt (st_4);
      *(b_44) = 83;
    }
    else
    {
      /* PERFORM Default Error Handler */
      frame_ptr++;
      if (unlikely(frame_ptr == frame_overflow))
      	cob_fatal_error (COB_FERROR_STACK);
      frame_ptr->perform_through = 1;
      frame_ptr->return_address_ptr = &&l_62;
      goto l_1;
      l_62:
      frame_ptr--;
    }
  }
  else
  {
    memmove (b_14, b_14, 52);
  }
  /* Line: 478       : DISPLAY            : TRANSF1A.cbl */
  module->module_stmt = 0x001001DE;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &c_43);
  /* Line: 479       : DISPLAY            : TRANSF1A.cbl */
  module->module_stmt = 0x001001DF;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 2, &c_44, &f_44);
  /* Line: 481       : DISPLAY            : TRANSF1A.cbl */
  module->module_stmt = 0x001001E1;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &c_45);

  /* Line: 485       : Paragraph 0009-END                : TRANSF1A.cbl */
  /* Line: 485       : EXIT               : TRANSF1A.cbl */
  module->module_stmt = 0x001001E5;
  cob_trace_stmt (st_5);

  /* Line: 493       : Section   9999-FINALIZAR          : TRANSF1A.cbl */
  l_36:;
  /* Line: 498       : DISPLAY            : TRANSF1A.cbl */
  module->module_stmt = 0x001001F2;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &c_46);
  /* Line: 499       : STOP RUN           : TRANSF1A.cbl */
  module->module_stmt = 0x001001F3;
  cob_trace_stmt (st_7);
  cob_stop_run (b_2);

  /* Line: 503       : Paragraph 9999-END                : TRANSF1A.cbl */
  /* Line: 503       : EXIT               : TRANSF1A.cbl */
  module->module_stmt = 0x001001F7;
  cob_trace_stmt (st_5);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 36)
    goto *frame_ptr->return_address_ptr;

  module->module_stmt = 0x001001F9;

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;


  /* Line: 0         : Paragraph Default Error Handler   : TRANSF1A.cbl */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS)) {
  	cob_fatal_error (COB_FERROR_FILE);
      goto l_1;
  }

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);

  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  TRANSF1A_module_init (module);

  module->crt_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  cob_set_llint (&f_2, 1000000000LL, (cob_s64_t)0);
  memset (b_21, 48, 10);
  memset (b_22, 48, 10);
  memset (b_23, 32, 20);
  cob_move ((cob_field *)&c_47, &f_24);
  cob_move ((cob_field *)&c_47, &f_25);
  memset (b_26, 32, 10);
  memset (b_27, 32, 20);
  cob_move ((cob_field *)&c_47, &f_28);
  memset (b_29, 32, 10);
  memset (b_30, 32, 20);
  cob_move ((cob_field *)&c_47, &f_31);
  *(b_32) = 48;
  *(cob_u8_ptr)(b_35) = 78;
  *(cob_u8_ptr)(b_36) = 78;
  memset (b_37, 48, 8);
  memset (b_38, 48, 6);
  cob_move (&cob_all_zero, &f_39);
  cob_move (&cob_all_zero, &f_40);
  cob_move (&cob_all_zero, &f_41);
  memset (b_42, 32, 60);
  memset (b_43, 0, 2);
  *(cob_u8_ptr)(b_44) = 78;
  memset (b_45, 48, 2);
  memset (b_46, 48, 10);
  memset (b_46 + 10, 32, 40);
  memset (b_46 + 50, 48, 11);
  memset (b_46 + 61, 32, 20);

  /* File initialization for CONTA-ENT */
  cob_file_create (&h_CONTA_ENT, NULL, "CONTA-ENT",
                   COB_ORG_LINE_SEQUENTIAL,COB_ACCESS_SEQUENTIAL,0,
                   COB_FILE_IS_DFLT,0,0,0,52,
                   (cob_field *)&c_48,&f_14);
  cob_file_complete (h_CONTA_ENT);

  /* File initialization for CONTA-SAI */
  cob_file_create (&h_CONTA_SAI, NULL, "CONTA-SAI",
                   COB_ORG_LINE_SEQUENTIAL,COB_ACCESS_SEQUENTIAL,0,
                   COB_FILE_IS_DFLT,0,0,0,200,
                   (cob_field *)&c_49,&f_17);
  cob_file_complete (h_CONTA_SAI);

  /* File initialization for TXT-LOG */
  cob_file_create (&h_TXT_LOG, NULL, "TXT-LOG",
                   COB_ORG_LINE_SEQUENTIAL,COB_ACCESS_SEQUENTIAL,0,
                   COB_FILE_IS_DFLT,0,0,0,200,
                   (cob_field *)&c_50,&f_20);
  cob_file_complete (h_TXT_LOG);

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:

  return 0;

}

/* End PROGRAM-ID 'TRANSF1A' */

/* Initialize module structure for TRANSF1A */
static void TRANSF1A_module_init (cob_module *module)
{
  module->module_name = "TRANSF1A";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())TRANSF1A;
  module->module_cancel.funcptr = (void *(*)())TRANSF1A_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = ',';
  module->currency_symbol = '$';
  module->numeric_separator = '.';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

